# Generated by Django 5.0.6 on 2024-06-17 02:42

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_id",
                    models.CharField(
                        default=webapp.models.get_default_item_id,
                        max_length=200,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store", models.CharField(max_length=200)),
                ("item_name", models.CharField(max_length=200)),
                ("item_type", models.CharField(default="Unknown", max_length=200)),
                ("category", models.CharField(default="Unknown", max_length=200)),
                (
                    "picture_link",
                    models.URLField(default="http://example.com/default.jpg"),
                ),
                ("brand", models.CharField(max_length=100)),
                ("price", models.FloatField(max_length=3)),
                ("link", models.URLField(default="http://example.com/default")),
            ],
        ),
        migrations.CreateModel(
            name="Similar_Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("store", models.CharField(max_length=200)),
                ("item_name", models.CharField(max_length=200)),
                (
                    "picture_link",
                    models.URLField(default="http://example.com/default.jpg"),
                ),
                ("price", models.CharField(max_length=200)),
                ("link", models.URLField(default="http://example.com/default")),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["store", "item_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("item_id",), name="unique_item_id"
            ),
        ),
        migrations.AddField(
            model_name="similar_item",
            name="original_item_id",
            field=models.ForeignKey(
                default=webapp.models.get_default_item,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.item",
            ),
        ),
        migrations.AddConstraint(
            model_name="similar_item",
            constraint=models.UniqueConstraint(
                fields=("original_item_id", "store", "item_name"),
                name="unique_similar_item",
            ),
        ),
    ]
