# Generated by Django 5.0.6 on 2024-06-13 21:36

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(unique=True)),
                ("store", models.CharField(max_length=200)),
                ("item_name", models.CharField(max_length=200)),
                ("item_type", models.CharField(max_length=200)),
                ("picture", models.ImageField(upload_to=webapp.models.get_upload_path)),
                ("brand", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=10)),
                ("price", models.FloatField(max_length=3)),
                ("sold", models.BooleanField(default=False)),
                ("link", models.TextField()),
                ("image_tags", models.TextField()),
            ],
            options={
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
                "ordering": ["store", "item_name"],
                "unique_together": {("product_id", "store")},
            },
        ),
    ]
