# Generated by Django 5.0.6 on 2024-06-17 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["store", "item_name"],
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
        migrations.AlterModelOptions(
            name="similar_item",
            options={},
        ),
    ]
