# Generated by Django 5.0.6 on 2024-06-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AddField(
            model_name="item",
            name="picture_link",
            field=models.URLField(default="Unknown"),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(default="Unknown", max_length=200),
        ),
        migrations.AlterField(
            model_name="item",
            name="link",
            field=models.URLField(default="Unknown"),
        ),
        migrations.RemoveField(
            model_name="item",
            name="picture",
        ),
        migrations.RemoveField(
            model_name="item",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="item",
            name="size",
        ),
        migrations.RemoveField(
            model_name="item",
            name="sold",
        ),
    ]
