# Generated by Django 5.0.6 on 2024-06-17 04:21

import django.db.models.deletion
import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_alter_item_options_alter_similar_item_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="similar_item",
            name="original_item_id",
            field=models.ForeignKey(
                default=webapp.models.get_default_item_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="webapp.item",
            ),
        ),
    ]
