# Generated by Django 5.0.6 on 2024-06-17 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_alter_similar_item_original_item_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="similar_item",
            options={"ordering": ["store", "item_name"]},
        ),
        migrations.RemoveConstraint(
            model_name="similar_item",
            name="unique_similar_item",
        ),
    ]
