# Generated by Django 5.0.6 on 2024-06-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_similar_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='similar_item',
            name='size',
            field=models.CharField(default='XS', max_length=400),
        ),
        migrations.AlterField(
            model_name='similar_item',
            name='item_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='similar_item',
            name='store',
            field=models.CharField(max_length=400),
        ),
    ]
