# Generated by Django 5.0.6 on 2024-06-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0006_similar_item_size_alter_similar_item_item_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=200)),
                ("account_creation", models.DateField()),
                ("password", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("total_water_saved", models.IntegerField(default=0)),
                ("total_amount_saved", models.FloatField(max_length=3)),
                ("loyalty_points", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["username"],
            },
        ),
        migrations.AlterField(
            model_name="similar_item",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XS", "Extra Small"),
                    ("XXL", "Extra Extra Large"),
                ],
                default="XS",
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseHistory",
            fields=[
                ("purchase_id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_date", models.DateField()),
                ("size", models.CharField(max_length=200)),
                ("item_price", models.FloatField(max_length=3)),
                ("amount_saved", models.FloatField(max_length=3)),
                ("water_saved", models.IntegerField()),
                ("loyalty", models.IntegerField()),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.item"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapp.user"
                    ),
                ),
            ],
            options={
                "ordering": ["purchase_id"],
            },
        ),
    ]
