# Generated by Django 5.0.6 on 2024-06-28 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0007_user_alter_similar_item_size_purchasehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasehistory",
            name="item_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapp.similar_item"
            ),
        ),
    ]
