# Generated by Django 5.0.6 on 2024-06-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0008_alter_purchasehistory_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
