# Generated by Django 5.0.6 on 2024-06-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0009_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_creation",
            field=models.DateField(auto_now_add=True),
        ),
    ]
