# Generated by Django 5.0.6 on 2024-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0010_alter_user_account_creation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="total_amount_saved",
            field=models.FloatField(default=0, max_length=3),
        ),
    ]
