# Generated by Django 5.0.6 on 2024-07-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "webapp",
            "0012_alter_user_managers_user_date_joined_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
