# Generated by Django 5.0.6 on 2024-07-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0013_remove_user_full_name_remove_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(default="unknown", max_length=200),
        ),
    ]
