# Generated by Django 5.0.6 on 2024-07-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0016_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
